/*
 * This file is generated by jOOQ.
 */
package me.peter.demo.db;


import javax.annotation.Generated;

import me.peter.demo.db.tables.FndUser;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>rbca</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FND_USER_PRIMARY = Indexes0.FND_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FND_USER_PRIMARY = Internal.createIndex("PRIMARY", FndUser.FND_USER, new OrderField[] { FndUser.FND_USER.ID }, true);
    }
}
