/*
 * This file is generated by jOOQ.
 */
package me.peter.demo.db;


import javax.annotation.Generated;

import me.peter.demo.db.tables.FndUser;


/**
 * Convenience access to all tables in rbca
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>rbca.fnd_user</code>.
     */
    public static final FndUser FND_USER = FndUser.FND_USER;
}
