/*
 * This file is generated by jOOQ.
 */
package me.peter.demo.db.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import me.peter.demo.db.tables.FndUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FndUserRecord extends UpdatableRecordImpl<FndUserRecord> implements Record10<Long, String, Integer, LocalDateTime, LocalDateTime, BigDecimal, String, String, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 618611731;

    /**
     * Setter for <code>rbca.fnd_user.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>rbca.fnd_user.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>rbca.fnd_user.name</code>. 姓名
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rbca.fnd_user.name</code>. 姓名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rbca.fnd_user.age</code>. 年龄
     */
    public void setAge(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>rbca.fnd_user.age</code>. 年龄
     */
    public Integer getAge() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>rbca.fnd_user.created_time</code>. 创建时间
     */
    public void setCreatedTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>rbca.fnd_user.created_time</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>rbca.fnd_user.updated_time</code>. 修改时间
     */
    public void setUpdatedTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>rbca.fnd_user.updated_time</code>. 修改时间
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>rbca.fnd_user.price</code>. 货币类型
     */
    public void setPrice(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>rbca.fnd_user.price</code>. 货币类型
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>rbca.fnd_user.summary</code>. 简述
     */
    public void setSummary(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>rbca.fnd_user.summary</code>. 简述
     */
    public String getSummary() {
        return (String) get(6);
    }

    /**
     * Setter for <code>rbca.fnd_user.intro</code>. 介绍
     */
    public void setIntro(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>rbca.fnd_user.intro</code>. 介绍
     */
    public String getIntro() {
        return (String) get(7);
    }

    /**
     * Setter for <code>rbca.fnd_user.lng</code>. 经度
     */
    public void setLng(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>rbca.fnd_user.lng</code>. 经度
     */
    public BigDecimal getLng() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>rbca.fnd_user.lat</code>. 纬度
     */
    public void setLat(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>rbca.fnd_user.lat</code>. 纬度
     */
    public BigDecimal getLat() {
        return (BigDecimal) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, Integer, LocalDateTime, LocalDateTime, BigDecimal, String, String, BigDecimal, BigDecimal> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, Integer, LocalDateTime, LocalDateTime, BigDecimal, String, String, BigDecimal, BigDecimal> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FndUser.FND_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return FndUser.FND_USER.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return FndUser.FND_USER.AGE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return FndUser.FND_USER.CREATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return FndUser.FND_USER.UPDATED_TIME;
    }

    @Override
    public Field<BigDecimal> field6() {
        return FndUser.FND_USER.PRICE;
    }

    @Override
    public Field<String> field7() {
        return FndUser.FND_USER.SUMMARY;
    }

    @Override
    public Field<String> field8() {
        return FndUser.FND_USER.INTRO;
    }

    @Override
    public Field<BigDecimal> field9() {
        return FndUser.FND_USER.LNG;
    }

    @Override
    public Field<BigDecimal> field10() {
        return FndUser.FND_USER.LAT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getAge();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedTime();
    }

    @Override
    public BigDecimal component6() {
        return getPrice();
    }

    @Override
    public String component7() {
        return getSummary();
    }

    @Override
    public String component8() {
        return getIntro();
    }

    @Override
    public BigDecimal component9() {
        return getLng();
    }

    @Override
    public BigDecimal component10() {
        return getLat();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getAge();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedTime();
    }

    @Override
    public BigDecimal value6() {
        return getPrice();
    }

    @Override
    public String value7() {
        return getSummary();
    }

    @Override
    public String value8() {
        return getIntro();
    }

    @Override
    public BigDecimal value9() {
        return getLng();
    }

    @Override
    public BigDecimal value10() {
        return getLat();
    }

    @Override
    public FndUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FndUserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public FndUserRecord value3(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public FndUserRecord value4(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public FndUserRecord value5(LocalDateTime value) {
        setUpdatedTime(value);
        return this;
    }

    @Override
    public FndUserRecord value6(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public FndUserRecord value7(String value) {
        setSummary(value);
        return this;
    }

    @Override
    public FndUserRecord value8(String value) {
        setIntro(value);
        return this;
    }

    @Override
    public FndUserRecord value9(BigDecimal value) {
        setLng(value);
        return this;
    }

    @Override
    public FndUserRecord value10(BigDecimal value) {
        setLat(value);
        return this;
    }

    @Override
    public FndUserRecord values(Long value1, String value2, Integer value3, LocalDateTime value4, LocalDateTime value5, BigDecimal value6, String value7, String value8, BigDecimal value9, BigDecimal value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FndUserRecord
     */
    public FndUserRecord() {
        super(FndUser.FND_USER);
    }

    /**
     * Create a detached, initialised FndUserRecord
     */
    public FndUserRecord(Long id, String name, Integer age, LocalDateTime createdTime, LocalDateTime updatedTime, BigDecimal price, String summary, String intro, BigDecimal lng, BigDecimal lat) {
        super(FndUser.FND_USER);

        set(0, id);
        set(1, name);
        set(2, age);
        set(3, createdTime);
        set(4, updatedTime);
        set(5, price);
        set(6, summary);
        set(7, intro);
        set(8, lng);
        set(9, lat);
    }
}
